# docker-compose down -v & git pull & docker-compose up --build
version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "8001:80"
    volumes:
      - static_volume:/app/static/
    depends_on:
      - django-app
    restart: "on-failure"

  rabbitmq:
    image:
      rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - django-app

  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: "on-failure"

  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate &&
                    python manage.py collectstatic &&
                    gunicorn lifelogger.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static/
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: "on-failure"

volumes:
  postgres_data:
  static_volume:
  rabbitmq:
  rabbitmq_logs:
