# Generated by Django 4.2 on 2023-05-07 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(5, 'Habit names should have between 5 and 50 characters.')
                ],
            ),
        ),
    ]
