# Generated by Django 4.2 on 2023-05-06 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('habits', '0004_habithistorylog_subscribedhabit_delete_userhabits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habithistorylog',
            old_name='updated_at',
            new_name='created_on',
        ),
    ]
